version: "2"

run:
  timeout: 2m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - bodyclose
    - nilerr
  disable:
    - revive  # Отключаем revive

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0