version: "3.9"

services:

  postgres:
    image: postgres:15-alpine
    container_name: currency-postgres
    environment:
      POSTGRES_USER: currency
      POSTGRES_PASSWORD: currency
      POSTGRES_DB: currency
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  currency-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: api
    container_name: currency
    environment:
      - GRPC_PORT=50051
      - DB_DSN=host=postgres port=5432 user=currency password=currency dbname=currency sslmode=disable
    ports:
      - "50051:50051"
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - backend

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: gateway
    container_name: gateway
    environment:
      - JWT_SECRET=super-secret-key
    ports:
      - "8080:8080"
    depends_on:
      - currency-api
      - auth-service
    networks:
      - backend

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: auth
    container_name: auth-service
    environment:
      - JWT_SECRET=super-secret-key
    ports:
      - "8082:8081"
    networks:
      - backend

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./deploy/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - backend

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: