// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/currency/transport/grpc/currency.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Rate          float64                `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`
	RateDate      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=rate_date,json=rateDate,proto3" json:"rate_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_internal_currency_transport_grpc_currency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_internal_currency_transport_grpc_currency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_internal_currency_transport_grpc_currency_proto_rawDescGZIP(), []int{0}
}

func (x *Currency) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Currency) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *Currency) GetRateDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RateDate
	}
	return nil
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_internal_currency_transport_grpc_currency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_currency_transport_grpc_currency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_internal_currency_transport_grpc_currency_proto_rawDescGZIP(), []int{1}
}

type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currencies    map[string]*Currency   `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_internal_currency_transport_grpc_currency_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_currency_transport_grpc_currency_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_internal_currency_transport_grpc_currency_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllResponse) GetCurrencies() map[string]*Currency {
	if x != nil {
		return x.Currencies
	}
	return nil
}

type GetOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneRequest) Reset() {
	*x = GetOneRequest{}
	mi := &file_internal_currency_transport_grpc_currency_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneRequest) ProtoMessage() {}

func (x *GetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_currency_transport_grpc_currency_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneRequest.ProtoReflect.Descriptor instead.
func (*GetOneRequest) Descriptor() ([]byte, []int) {
	return file_internal_currency_transport_grpc_currency_proto_rawDescGZIP(), []int{3}
}

func (x *GetOneRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetOneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      *Currency              `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneResponse) Reset() {
	*x = GetOneResponse{}
	mi := &file_internal_currency_transport_grpc_currency_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneResponse) ProtoMessage() {}

func (x *GetOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_currency_transport_grpc_currency_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneResponse.ProtoReflect.Descriptor instead.
func (*GetOneResponse) Descriptor() ([]byte, []int) {
	return file_internal_currency_transport_grpc_currency_proto_rawDescGZIP(), []int{4}
}

func (x *GetOneResponse) GetCurrency() *Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

var File_internal_currency_transport_grpc_currency_proto protoreflect.FileDescriptor

const file_internal_currency_transport_grpc_currency_proto_rawDesc = "" +
	"\n" +
	"/internal/currency/transport/grpc/currency.proto\x12\bcurrency\x1a\x1fgoogle/protobuf/timestamp.proto\"k\n" +
	"\bCurrency\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x01R\x04rate\x127\n" +
	"\trate_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\brateDate\"\x0f\n" +
	"\rGetAllRequest\"\xad\x01\n" +
	"\x0eGetAllResponse\x12H\n" +
	"\n" +
	"currencies\x18\x01 \x03(\v2(.currency.GetAllResponse.CurrenciesEntryR\n" +
	"currencies\x1aQ\n" +
	"\x0fCurrenciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.currency.CurrencyR\x05value:\x028\x01\"#\n" +
	"\rGetOneRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"@\n" +
	"\x0eGetOneResponse\x12.\n" +
	"\bcurrency\x18\x01 \x01(\v2\x12.currency.CurrencyR\bcurrency2\xb2\x02\n" +
	"\x0fCurrencyService\x12;\n" +
	"\x06GetAll\x12\x17.currency.GetAllRequest\x1a\x18.currency.GetAllResponse\x12;\n" +
	"\x06GetOne\x12\x17.currency.GetOneRequest\x1a\x18.currency.GetOneResponse\x120\n" +
	"\x06Create\x12\x12.currency.Currency\x1a\x12.currency.Currency\x123\n" +
	"\tUpdateOne\x12\x12.currency.Currency\x1a\x12.currency.Currency\x12>\n" +
	"\tSyncRates\x12\x17.currency.GetAllRequest\x1a\x18.currency.GetAllResponseB\x19Z\x17internal/currency/protob\x06proto3"

var (
	file_internal_currency_transport_grpc_currency_proto_rawDescOnce sync.Once
	file_internal_currency_transport_grpc_currency_proto_rawDescData []byte
)

func file_internal_currency_transport_grpc_currency_proto_rawDescGZIP() []byte {
	file_internal_currency_transport_grpc_currency_proto_rawDescOnce.Do(func() {
		file_internal_currency_transport_grpc_currency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_currency_transport_grpc_currency_proto_rawDesc), len(file_internal_currency_transport_grpc_currency_proto_rawDesc)))
	})
	return file_internal_currency_transport_grpc_currency_proto_rawDescData
}

var file_internal_currency_transport_grpc_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_currency_transport_grpc_currency_proto_goTypes = []any{
	(*Currency)(nil),              // 0: currency.Currency
	(*GetAllRequest)(nil),         // 1: currency.GetAllRequest
	(*GetAllResponse)(nil),        // 2: currency.GetAllResponse
	(*GetOneRequest)(nil),         // 3: currency.GetOneRequest
	(*GetOneResponse)(nil),        // 4: currency.GetOneResponse
	nil,                           // 5: currency.GetAllResponse.CurrenciesEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_internal_currency_transport_grpc_currency_proto_depIdxs = []int32{
	6, // 0: currency.Currency.rate_date:type_name -> google.protobuf.Timestamp
	5, // 1: currency.GetAllResponse.currencies:type_name -> currency.GetAllResponse.CurrenciesEntry
	0, // 2: currency.GetOneResponse.currency:type_name -> currency.Currency
	0, // 3: currency.GetAllResponse.CurrenciesEntry.value:type_name -> currency.Currency
	1, // 4: currency.CurrencyService.GetAll:input_type -> currency.GetAllRequest
	3, // 5: currency.CurrencyService.GetOne:input_type -> currency.GetOneRequest
	0, // 6: currency.CurrencyService.Create:input_type -> currency.Currency
	0, // 7: currency.CurrencyService.UpdateOne:input_type -> currency.Currency
	1, // 8: currency.CurrencyService.SyncRates:input_type -> currency.GetAllRequest
	2, // 9: currency.CurrencyService.GetAll:output_type -> currency.GetAllResponse
	4, // 10: currency.CurrencyService.GetOne:output_type -> currency.GetOneResponse
	0, // 11: currency.CurrencyService.Create:output_type -> currency.Currency
	0, // 12: currency.CurrencyService.UpdateOne:output_type -> currency.Currency
	2, // 13: currency.CurrencyService.SyncRates:output_type -> currency.GetAllResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_currency_transport_grpc_currency_proto_init() }
func file_internal_currency_transport_grpc_currency_proto_init() {
	if File_internal_currency_transport_grpc_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_currency_transport_grpc_currency_proto_rawDesc), len(file_internal_currency_transport_grpc_currency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_currency_transport_grpc_currency_proto_goTypes,
		DependencyIndexes: file_internal_currency_transport_grpc_currency_proto_depIdxs,
		MessageInfos:      file_internal_currency_transport_grpc_currency_proto_msgTypes,
	}.Build()
	File_internal_currency_transport_grpc_currency_proto = out.File
	file_internal_currency_transport_grpc_currency_proto_goTypes = nil
	file_internal_currency_transport_grpc_currency_proto_depIdxs = nil
}
