// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: currency.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Rate          string                 `protobuf:"bytes,2,opt,name=rate,proto3" json:"rate,omitempty"` // DECIMAL
	RateDate      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=rate_date,json=rateDate,proto3" json:"rate_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_currency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{0}
}

func (x *Currency) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Currency) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *Currency) GetRateDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RateDate
	}
	return nil
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_currency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{1}
}

type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currencies    map[string]*Currency   `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_currency_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllResponse) GetCurrencies() map[string]*Currency {
	if x != nil {
		return x.Currencies
	}
	return nil
}

type GetOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneRequest) Reset() {
	*x = GetOneRequest{}
	mi := &file_currency_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneRequest) ProtoMessage() {}

func (x *GetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneRequest.ProtoReflect.Descriptor instead.
func (*GetOneRequest) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{3}
}

func (x *GetOneRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetAtDateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAtDateRequest) Reset() {
	*x = GetAtDateRequest{}
	mi := &file_currency_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAtDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAtDateRequest) ProtoMessage() {}

func (x *GetAtDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAtDateRequest.ProtoReflect.Descriptor instead.
func (*GetAtDateRequest) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{4}
}

func (x *GetAtDateRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetAtDateRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type GetRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRangeRequest) Reset() {
	*x = GetRangeRequest{}
	mi := &file_currency_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRangeRequest) ProtoMessage() {}

func (x *GetRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRangeRequest.ProtoReflect.Descriptor instead.
func (*GetRangeRequest) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{5}
}

func (x *GetRangeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetRangeRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetRangeRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type GetOneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      *Currency              `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneResponse) Reset() {
	*x = GetOneResponse{}
	mi := &file_currency_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneResponse) ProtoMessage() {}

func (x *GetOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneResponse.ProtoReflect.Descriptor instead.
func (*GetOneResponse) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{6}
}

func (x *GetOneResponse) GetCurrency() *Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

type GetRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currencies    []*Currency            `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRangeResponse) Reset() {
	*x = GetRangeResponse{}
	mi := &file_currency_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRangeResponse) ProtoMessage() {}

func (x *GetRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRangeResponse.ProtoReflect.Descriptor instead.
func (*GetRangeResponse) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{7}
}

func (x *GetRangeResponse) GetCurrencies() []*Currency {
	if x != nil {
		return x.Currencies
	}
	return nil
}

var File_currency_proto protoreflect.FileDescriptor

const file_currency_proto_rawDesc = "" +
	"\n" +
	"\x0ecurrency.proto\x12\bcurrency\x1a\x1fgoogle/protobuf/timestamp.proto\"k\n" +
	"\bCurrency\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\tR\x04rate\x127\n" +
	"\trate_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\brateDate\"\x0f\n" +
	"\rGetAllRequest\"\xad\x01\n" +
	"\x0eGetAllResponse\x12H\n" +
	"\n" +
	"currencies\x18\x01 \x03(\v2(.currency.GetAllResponse.CurrenciesEntryR\n" +
	"currencies\x1aQ\n" +
	"\x0fCurrenciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.currency.CurrencyR\x05value:\x028\x01\"#\n" +
	"\rGetOneRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"V\n" +
	"\x10GetAtDateRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12.\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"\x81\x01\n" +
	"\x0fGetRangeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"@\n" +
	"\x0eGetOneResponse\x12.\n" +
	"\bcurrency\x18\x01 \x01(\v2\x12.currency.CurrencyR\bcurrency\"F\n" +
	"\x10GetRangeResponse\x122\n" +
	"\n" +
	"currencies\x18\x01 \x03(\v2\x12.currency.CurrencyR\n" +
	"currencies2\xd4\x02\n" +
	"\x0fCurrencyService\x12;\n" +
	"\x06GetAll\x12\x17.currency.GetAllRequest\x1a\x18.currency.GetAllResponse\x12>\n" +
	"\tGetLatest\x12\x17.currency.GetOneRequest\x1a\x18.currency.GetOneResponse\x12A\n" +
	"\tGetAtDate\x12\x1a.currency.GetAtDateRequest\x1a\x18.currency.GetOneResponse\x12A\n" +
	"\bGetRange\x12\x19.currency.GetRangeRequest\x1a\x1a.currency.GetRangeResponse\x12>\n" +
	"\tSyncRates\x12\x17.currency.GetAllRequest\x1a\x18.currency.GetAllResponseB\x19Z\x17internal/currency/protob\x06proto3"

var (
	file_currency_proto_rawDescOnce sync.Once
	file_currency_proto_rawDescData []byte
)

func file_currency_proto_rawDescGZIP() []byte {
	file_currency_proto_rawDescOnce.Do(func() {
		file_currency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_currency_proto_rawDesc), len(file_currency_proto_rawDesc)))
	})
	return file_currency_proto_rawDescData
}

var file_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_currency_proto_goTypes = []any{
	(*Currency)(nil),              // 0: currency.Currency
	(*GetAllRequest)(nil),         // 1: currency.GetAllRequest
	(*GetAllResponse)(nil),        // 2: currency.GetAllResponse
	(*GetOneRequest)(nil),         // 3: currency.GetOneRequest
	(*GetAtDateRequest)(nil),      // 4: currency.GetAtDateRequest
	(*GetRangeRequest)(nil),       // 5: currency.GetRangeRequest
	(*GetOneResponse)(nil),        // 6: currency.GetOneResponse
	(*GetRangeResponse)(nil),      // 7: currency.GetRangeResponse
	nil,                           // 8: currency.GetAllResponse.CurrenciesEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_currency_proto_depIdxs = []int32{
	9,  // 0: currency.Currency.rate_date:type_name -> google.protobuf.Timestamp
	8,  // 1: currency.GetAllResponse.currencies:type_name -> currency.GetAllResponse.CurrenciesEntry
	9,  // 2: currency.GetAtDateRequest.date:type_name -> google.protobuf.Timestamp
	9,  // 3: currency.GetRangeRequest.from:type_name -> google.protobuf.Timestamp
	9,  // 4: currency.GetRangeRequest.to:type_name -> google.protobuf.Timestamp
	0,  // 5: currency.GetOneResponse.currency:type_name -> currency.Currency
	0,  // 6: currency.GetRangeResponse.currencies:type_name -> currency.Currency
	0,  // 7: currency.GetAllResponse.CurrenciesEntry.value:type_name -> currency.Currency
	1,  // 8: currency.CurrencyService.GetAll:input_type -> currency.GetAllRequest
	3,  // 9: currency.CurrencyService.GetLatest:input_type -> currency.GetOneRequest
	4,  // 10: currency.CurrencyService.GetAtDate:input_type -> currency.GetAtDateRequest
	5,  // 11: currency.CurrencyService.GetRange:input_type -> currency.GetRangeRequest
	1,  // 12: currency.CurrencyService.SyncRates:input_type -> currency.GetAllRequest
	2,  // 13: currency.CurrencyService.GetAll:output_type -> currency.GetAllResponse
	6,  // 14: currency.CurrencyService.GetLatest:output_type -> currency.GetOneResponse
	6,  // 15: currency.CurrencyService.GetAtDate:output_type -> currency.GetOneResponse
	7,  // 16: currency.CurrencyService.GetRange:output_type -> currency.GetRangeResponse
	2,  // 17: currency.CurrencyService.SyncRates:output_type -> currency.GetAllResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_currency_proto_init() }
func file_currency_proto_init() {
	if File_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_currency_proto_rawDesc), len(file_currency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_currency_proto_goTypes,
		DependencyIndexes: file_currency_proto_depIdxs,
		MessageInfos:      file_currency_proto_msgTypes,
	}.Build()
	File_currency_proto = out.File
	file_currency_proto_goTypes = nil
	file_currency_proto_depIdxs = nil
}
